# Generated by Django 3.1.3 on 2020-11-14 02:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_print_job_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bid', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('details', models.TextField()),
                ('print_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.printjob')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='printjob',
            name='accepted_vendor_offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.vendoroffer'),
        ),
    ]
