# Generated by Django 3.1.3 on 2020-11-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_print_job_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='dimension_unit',
            field=models.CharField(choices=[('in', 'inches'), ('cm', 'centimeters'), ('mm', 'millimeters')], default='mm', max_length=2),
            preserve_default=False,
        ),
    ]
