# Generated by Django 3.1.3 on 2020-11-14 04:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_is_vendor_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dimension_unit', models.CharField(choices=[('in', 'inches'), ('cm', 'centimeters')], max_length=2)),
                ('filaments', models.CharField(max_length=1000)),
                ('make', models.CharField(max_length=100)),
                ('max_print_dimension_x', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_print_dimension_y', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_print_dimension_z', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('model', models.CharField(max_length=150)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
