# Generated by Django 3.1.3 on 2020-11-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_printer_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='dimension_unit',
            field=models.CharField(choices=[('in', 'inches'), ('cm', 'centimeters'), ('mm', 'millimeters')], max_length=2),
        ),
    ]
